examples/vallina/index.html
No need to indicate which browsers this is for, as it is still appropriate for newer browsers to illustrate a simple usage of the SDK.
=> Remove unnecessary comment from demo app

package.json
Following the move of the repo we have renamed links to harness
=> (maint) Update references from drone to harness

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, package-lock.json, package.json, src/index.ts
This PR restricts incrementing metrics to prevent all flags being marked as accessed on initial load. It also guards against triggering metrics with a `0` count.
=> feat: [FFM-6788]: Restrict metric incrementation

.github/workflows/notify_release.yml
This PR updates the version of `slackapi/slack-github-action` to a version which uses a version of Node that GitHub supports. No changes to the SDK are included in this.
=> chore: [FFM-7063]: Update slack-github-action

src/index.ts, src/types.ts
**Changes**
If the flag evaluation is sent directly in the sse stream save it and don't query SaaS. 
If the flag evaluation isn't sent then query SaaS for the updated value as normal. 
It shouldn't happen but we have defensive code here that makes sure every field is correctly populated before we save, else we'll fallback to polling as normal. 
**Impact**
Once the stream is connected we can get and use updated flag values without needing to make any requests to SaaS, meaning lower latency and fewer network calls for customers sdks. 
https://github.com/harness/ff-javascript-client-sdk/assets/42169772/1b4718fc-6b40-4445-a5cd-a50e5afe1cdd
=> (FFM-7896) Handle evaluation sse events

src/index.ts, src/types.ts
**Changes**
Support evaluations being sent directly through target-segment sse events.
Update flag events to also use the evaluations structure, matching the latest design changes on ff-server
=> (FFM-8144) Target group pre-evaluation logic

README.md, examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, mobile_device_support.md, package-lock.json, package.json, src/index.ts, src/types.ts
FFM-8141 - Add refreshEvaluations() API method to allow webviews inside mobile apps coming to foreground to get latest flags
What
Adds a new function called refreshEvaluations() to CfClient
Why
This change adds a new API called refreshEvaluations() which can be called by a mobile app using the SDK in a webview coming to the foreground to update any SSE flag events that were missed while the app was suspended. Note this new API should not be used to poll the Feature Flags server, it will only retrieve evaluations from the server if enough time has elapsed to avoid putting to much pressure on the backend.
It's up to the native app to call this JS method from the webview APIs when the app comes to foreground.
Testing
Manual. Tested with Xcode + iOS Simulator with a WKWebView
=> FFM-8141 - Add refreshEvaluations() API method

README.md, package-lock.json, package.json, src/__tests__/poller.test.ts, src/index.ts, src/poller.ts, src/stream.ts, src/types.ts
When `close()` is called, the heartbeat monitor still runs and logs an error that the SSE connection times out. This update clears that heartbeat monitor interval when close is ran. 
Also adds polling events
So we don't log timeout errors when the stream is closed 
Manual
=> FFM-8964 - Stop hearbeat monitor when `close()` is called

README.md, package-lock.json, package.json, src/__tests__/poller.test.ts, src/index.ts, src/poller.ts, src/stream.ts, src/types.ts
Emits a new POLLING_CHANGED event which includes the response from `fetchFlags` 
This is achieved by updating the `fetchFlags` signature, instead of having it return a void promise on success and error on failure
So consumers can access the polled flags
Manual 
- Flags are fetched by `fetchFlags` and emitted in the new event correctly. 
- Updated poller unit tests
=> FFM-9045 Emit flags as part of polling intervals

package-lock.json, package.json, src/types.ts, src/utils.ts
Deprecates from `Options`: 
- `allAttributesPrivate`
- `privateAttributeNames` 
These Options properties were never supported or implemented correctly, and should not have been included in the API.
=> FFM-9776 Deprecate unsupported options

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, package-lock.json, package.json, src/__tests__/cache.test.ts, src/cache.ts, src/index.ts
This PR updates how the SDK builds the cache id to take into account the SDK Key to ensure that if multiple SDKs are in use in the same page using the same target id, they will have separate caches.
=> feat: [FFM-10231]: Use SHA-256 hash of target id and sdk key as cache id

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, package-lock.json, package.json, src/index.ts
This PR puts defensive code around the usage of `btoa`. In React Native this function reports as not being present, which prevents the React SDK being used in React Native.
=> feat: [FFM-10455]: Add defensive code around btoa usage

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, package-lock.json, package.json, src/index.ts
**What**
Make the JS SDK fall back to polling when it detects that it is running inside Android on React native
**Why**
XMLHttpRequest does not work correctly on React Native when Android is used. For more context: https://github.com/facebook/react-native/issues/28835 We will use this work around until a better fix is identified.
**Testing**
Manual
=> [FFM-10442] - Disable streaming if Reactive Native + Android is detected

README.md, package-lock.json, package.json, src/__tests__/cache.test.ts, src/__tests__/utils.test.ts, src/cache.ts, src/index.ts, src/types.ts, src/utils.ts
This PR updates the cache support to allow overriding of the cache storage mechanism from the default of `localStorage` to instead being any class that's compatible with the Web Storage API standard. The cache mechanism can also be asynchronous. This PR also adds information about each of the configuration options, removes 2 previously deprecated config options and removes code which stores metrics to `localStorage` on shutdown.
=> feat: [FFM-10772]: Allow override of cache storage mechanism

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, src/index.ts, src/utils.ts
Unfortunately the solution to detect React Native running on Android caused issues with typescript projects and a warning being displayed; this PR removes that detection. This PR also adds an extra debug message and updates the examples' dependencies.
=> fix: [FFM-10810]: Remove React Native Android detection

examples/preact/package-lock.json, examples/react-redux/package-lock.json, examples/react/package-lock.json, package-lock.json, package.json, src/stream.ts
- Now logs stream disconnect & timeouts as `debug` instead of `error`
- An `error` will be logged if reconnection is still being attempted after every `5, 10, 15...` attempts
We expect occasional stream disconnects/timeouts and the SDK will "self-heal" by reconnecting. Logging these as errors in the first instance is misleading and can cause users to be concerned unjustifiably.
Manual - using proxy tool to simulate disconnects.
=> FFM-10924 Streaming disconnect log level changes

package-lock.json, package.json
Runs  `npm audit fix` to patch 
1. CVE-2024-37890
2. CVE-2024-4068
=> Maintenance: Patch CVEs

README.md, package-lock.json, package.json, src/__tests__/stream.test.ts, src/index.ts, src/stream.ts, src/types.ts, src/utils.ts
Adds a config option called `maxStreamRetries` to limit the retries that occur if the stream disconnects.  By default, the retries remain at `Infinite` which is the existing behaviour.  If retries are exhausted, one of two states can occur
1. If Polling is enabled, the SDK will remain in polling mode and no further streaming reconnection attempts will be made.  The default polling option, if not supplied, is whatever the `streamingEnabled` value is. 
or 
2. If polling is disabled, the SDK will not get any further evaluation updates for the remainder of the SDK client instance's life. The SDK will need re-initialised, e.g the app being restarted, to get new evaluations in this state.
A customer has asked for a way to limit stream retries
New unit tests for the `Streamer` class. 
Manual …
=> FFM-11788 Add `maxStreamRetries` config option 

package-lock.json, package.json, src/poller.ts
Fixes an edge case where if the stream disconnects and resumes during a request made by the fallback poller (60 seconds later), the fallback poller will not be disabled and will continue polling for the lifetime of the SDK instance.
Manual using local proxy tool to simulate stream disconnects and observed no third `evaluations` request once the stream reconnected.
=> FFM-11852 Stop fallback Poller if stream resumes during a polling request

README.md, package-lock.json, package.json, src/__tests__/stream.test.ts, src/index.ts, src/types.ts, src/utils.ts
Adds configuration option `authRequestReadTimeout` which allows users to specify a timeout for the authentication request made by the SDK. The default value is `0` (to keep backwards compatability) which means no timeout will occur.  If set to a value greater than `0`, the request will abort. An error will be logged and the `ERROR_AUTH` and `ERROR` events will be emitted. 
For older browsers (prior to 2016) which do not support the `AbortController`;  if `authRequestReadTimeout` is configured the auth request will proceed without a timeout and a warning will be logged.
Also patches https://github.com/advisories/GHSA-952p-6rrq-rcjv. This is found in `micromatch` which is used by dev dependencies and not shipped to users.
- @types/jest@29.5.4
- "jest": "^29.6.4",
Using a local proxy tool to …
=> FFM-11972 Add `authRequestReadTimeout` option

README.md, package-lock.json, package.json, src/__tests__/variation.test.ts, src/index.ts, src/types.ts, src/variation.ts
Adds new event `ERROR_DEFAULT_VARIATION_RETURNED` that is emitted whenever a default variation is returned. 
- Updated unit tests
- Manual with prod2 account
=> FFM-12129 Add new event for default variation being returned

README.md, package-lock.json, package.json, src/__tests__/cache.test.ts, src/cache.ts, src/index.ts, src/types.ts, src/utils.ts
This PR adds the new `deriveKeyFromTargetAttributes` cache config option. This allows the use of target attributes when building up the key that's used to store and retrieve evaluations from the cache.
```typescript
// use all attributes when deriving key
const client = initialize(apiKey, target, {
cache: {
deriveKeyFromTargetAttributes: true
}
})
// use subset of attributes when deriving key
const client = initialize(apiKey, target, {
cache: {
deriveKeyFromTargetAttributes: ['attributeA', 'attributeB']
}
})
```
=> feat: [FFM-12306]: Enhance caching key

README.md, package-lock.json, package.json, src/index.ts, src/types.ts, src/utils.ts
- Exposes `enableAnalytics` to control whether metrics are sent
- Bumps `esbuild` due to CVE. Minimum Node version to build the SDK is now 18. Note that this is a dev dependency so doesn't alter existing min supported version for users.
Manual
=> FFM-12373 Add option to disable metrics

README.md, package-lock.json, package.json, src/__tests__/stream.test.ts, src/index.ts, src/stream.ts
Usage example to add a custom header to SDK `/stream` requests:
```js
const ffClient = initialize(
sdkKey, {
identifier: id,
});
ffClient.registerAPIRequestMiddleware(([url, options]) => {
if (url.includes('/stream')) {
options.headers['X-Custom-Header'] = 'CustomValue';
}
return [url, options];
});
```
=> Fix: apply `client.registerAPIRequestMiddleware` to SDK streaming requests
